# This is the main configuration file for SpigotX.
# Modify with caution, and make sure you know what you are doing.

knockback:
  current: default
  profiles: {}
hide-players-from-tab: true
fire-player-move-event: false
fire-left-click-air: false
fire-left-click-block: false
entity-activation: false
invalid-arm-animation-kick: true
mob-ai: true
1-8-enabled: true
do-chunk-unload: true
block-operations: false
disable-join-message: true
disable-leave-message: true
disable-op: false
